version: "3.3"
services:
  vegebot:
    image: isaacirvine/vegebot
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_BOT_TOKEN}
      POSTGREST_TOKEN: ${POSTGREST_TOKEN}
      POSTGREST_URL: http://postgrest:3000
      POSTGRES_HOST: postgres
      POSTGRES_DB: vege_db
      POSTGRES_USER: auth
      WEBAPP_URL: vegestats.isaacirvine.me
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgrest
  postgrest:
    restart: always
    image: postgrest/postgrest
    environment:
      PGRST_JWT_SECRET: ${POSTGREST_JWT_SECRET}
      PGRST_DB_URI: postgres://auth:${POSTGRES_PASSWORD}@postgres:5432/vege_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: vege_db
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  vegestats:
    image: tomay0/vegestats
    depends_on:
      - postgrest
    restart: always
    environment:
      POSTGREST_TOKEN: ${POSTGREST_TOKEN}
      POSTGREST_URL: postgrest
      APP_PORT: 80
volumes:
  pgdata:
networks:
  default:
    external:
      name: proxymanager
